app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb
Finished the set-up for devise
=> finished the devise set-up

app/models/category.rb, app/models/review.rb, app/models/side_quest.rb, app/models/stop.rb, app/models/trip.rb, app/models/user.rb, config/routes.rb
Added validations and associations  for all the models
=> completed the validations for all the models and the associations

app/controllers/reviews_controller.rb, app/controllers/sidequests_controller.rb, app/controllers/trips_controller.rb, app/models/category.rb, app/models/side_quest.rb, app/models/trip.rb, db/seeds.rb, test/controllers/reviews_controller_test.rb, test/controllers/sidequests_controller_test.rb, test/controllers/trips_controller_test.rb
Adding seeds
We need to comment out the geocode from the sidequest model
=> adding seeds

Gemfile, Gemfile.lock, app/models/side_quest.rb, config/environment.rb, config/storage.yml, db/migrate/20221119204046_create_active_storage_tables.active_storage.rb, db/schema.rb
Added cloudinary with active storage and dotenv
=> completed set-up for cloudinary and dotenv

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, config/environment.rb, config/initializers/geocoder.rb, db/migrate/20221119210737_add_coordinates_to_side_quest.rb, db/schema.rb
added geocoder gem and did initial set-up
=> added geocoder

app/controllers/category_controller.rb, app/controllers/pages_controller.rb, app/controllers/sidequests_controller.rb, app/controllers/trips_controller.rb, app/views/pages/home.html.erb, app/views/reviews/show.html.erb, app/views/sidequests/index.html.erb, app/views/sidequests/new.html.erb, app/views/sidequests/show.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb, db/schema.rb, test/controllers/category_controller_test.rb
Adding seed file 
Adding methods to SideQuest and Trip
Adding Views to SideQuest and Trip
=> adding methods and views

app/controllers/application_controller.rb, app/controllers/sidequests_controller.rb, app/controllers/users_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, db/schema.rb, test/controllers/users_controller_test.rb
Added image upload function for user model and for
=>  added images for user model and for side_quest model

Gemfile.lock, app/assets/stylesheets/components/_modal.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/reviews_controller.rb, app/controllers/trips_controller.rb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb, app/views/reviews/show.html.erb, app/views/shared/_navbar.html.erb, app/views/sidequests/_form.html.erb, app/views/sidequests/_modal.html.erb, app/views/sidequests/index.html.erb, app/views/sidequests/new.html.erb, app/views/sidequests/show.html.erb, app/views/trips/new.html.erb, package.json, yarn.lock
- made a template for the modal for side quests
- form partial for reviews
- declared the css colours in the stylesheets/config
- modal basic css with 'x' close feature
- commented out the upload feature on user registration it has bugs
- basic container structuring on all the pages
- updated bootstrap gem
- removed the 'messages' nav-link from the nav-bar
- added actions my side quests & my trips in the nav-bar dropdown
=> Css varariable

app/views/shared/_navbar.html.erb, app/views/side_quests/show.html.erb
=> map completed and api key added

db/seeds.rb
=> database seeded. Images missing

app/views/layouts/application.html.erb, db/migrate/20221126164316_add_coordinates_to_trips.rb, db/migrate/20221126164414_add_end_coordinates_to_trips.rb, db/schema.rb
=> Add coordinates trips

app/views/side_quests/index.html.erb, app/views/side_quests/show.html.erb
Adding links to sidequest to redirect from index to show page
=> adding links to the index page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_trip_card.scss, app/controllers/trips_controller.rb, app/javascript/controllers/map_controller.js, app/views/layouts/application.html.erb, app/views/reviews/show.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb
- fixed the footer and the button displays at the bottom
- trip-card added showing start and end with the side quests
=> Trips id review show page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_homepage.scss, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/reviews/_form.html.erb, app/views/side_quests/index.html.erb, app/views/side_quests/show.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb
- fixed footer container 
- background color fixed
- general alignment done
=> general front-end clean up v2

app/views/side_quests/index.html.erb
Adding map to index  and longitue and latitude properties to all sidequests
=> Fixing new trip and show trip issue

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_photo-sidequest.scss, app/assets/stylesheets/components/_preferences-form.scss, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, app/views/trips/new.html.erb
- photo positioning done (using seb saunier as a template)- trips/new
- and the preferences form
- commented out the carousel from bootstrap for now until cloudinary is integrated
- fixed alerts and notifications
=> Front end update v2

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_homepage.scss, app/assets/stylesheets/components/_index.scss, app/controllers/category_controller.rb, app/controllers/locations_controller.rb, app/controllers/pages_controller.rb, app/controllers/side_quests_controller.rb, app/controllers/trips_controller.rb, app/views/reviews/_form.html.erb, app/views/reviews/index.html.erb, app/views/reviews/new.html.erb, app/views/side_quests/_form.html.erb, app/views/side_quests/index.html.erb, app/views/side_quests/show.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb
-button styling and sqs/show review layout done 
-footer styling 
-general layout work
=> button styling and layout

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_sidequest-cards.scss, app/assets/stylesheets/components/_trip-card.scss, app/controllers/trips_controller.rb, app/views/side_quests/_sidequest_list.html.erb, app/views/side_quests/index.html.erb, app/views/side_quests/show.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb
-further layout upgrades 
- debugging of sqs/show
- component creation
=> Front end update v4

app/controllers/stops_controller.rb, app/views/side_quests/_info_window.html.erb, config/routes.rb, test/controllers/stops_controller_test.rb
Adding stops to trips.
I still need to work on the front-end aspect once stops are added to the trip
Need to add a "start my trip button" to index
=> adding stops to trips

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb, app/views/side_quests/_form.html.erb, app/views/side_quests/new.html.erb, app/views/trips/show.html.erb
- sqs/new form done with icons 
- navbar added removed the weird 3 stripe toggle in the navbar and kept the avatar for better ux
-updated the logic in the navbar for actions while logged in and when logged off
=> Front end update mobilev2

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
- navbar dynamic with positioning of components
- further code clean up of the navbar partial and components (removal of unnecessary code)
- logic for the back button code structure in the navbar partial but commented out for Ricardo controller stuff
=> Front updatev2

app/helpers/application_helper.rb, app/views/shared/_navbar.html.erb
Going back to previous nav bar until the new one is functional
=> nav bar needs fix

app/assets/stylesheets/components/_trip-card.scss, app/views/trips/show.html.erb
=> Centered and changed fonts

app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/views/shared/_navbar.html.erb, app/views/side_quests/show.html.erb, app/views/trips/new.html.erb
- back btn functional 
- removal of unnecessary css rules in the navbar
=> Front end updatev3

app/views/shared/_navbar.html.erb, app/views/trips/index.html.erb, app/views/trips/mytrips.html.erb, app/views/trips/new.html.erb, config/routes.rb
- nav bar routing links fixed
- routes changes for sqs/new & create (removing from the trips nest)
- my trips page created work in progress
=> routes mods and navbar alterations

app/controllers/application_controller.rb, app/helpers/meta_tags_helper.rb, app/views/layouts/application.html.erb, config/initializers/default_meta.rb, config/meta.yml
- added three files to configure default meta data
- modified root view HTML to include these default tags
=> adding relavant title tags to the app

.gitignore, Gemfile, app/models/side_quest.rb, app/views/shared/_navbar.html.erb, app/views/side_quests/show.html.erb, app/views/trips/_info_window.html.erb, config/environments/development.rb, config/storage.yml, db/seeds.rb
Adding reviews 
Adding Cloudinary 
Adding photos to sidequests
=> Adding images

app/assets/stylesheets/components/_trip-card.scss, app/controllers/trips_controller.rb, app/views/trips/index.html.erb, app/views/trips/new.html.erb
- My Trips page work done 
- listing all the trips with the side quests taken
=> My trips page

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_sidequest-cards.scss, app/controllers/reviews_controller.rb, app/views/layouts/application.html.erb, app/views/side_quests/show.html.erb, config/routes.rb
- resdesigned the sidequests/show page that is accessed from hitting "explore" on the modals
=> Routing errors

app/controllers/trips_controller.rb, app/views/trips/_info_window.html.erb, app/views/trips/edit.html.erb, app/views/trips/show.html.erb
- trips/edit page layout changes 
- map full width
- still working on displaying full size modals for the pins
=> Sqs info window front end

Gemfile.lock, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_homepage.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_textitems.scss, app/assets/stylesheets/components/_trip-card.scss, app/controllers/trips_controller.rb, app/javascript/controllers/map_controller.js, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/trips/_info_window.html.erb, app/views/trips/edit.html.erb, app/views/trips/index.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb
- Fix meta tag to properly render the page on mobile
- Vertically align text in some CTAs
- Fix map position & size in trips show and edit pages
- Fix usability of the sidequest map popup. Add a vertical scroll to the description so that the popup does not take too much space.
- Fix styling of the trip instruction card
- Fix navbar Sidequest Logo margin making it not centered
- Add container to some views
- Various indentation and minor refactorings for better clarity
=> UI Hotfixes

app/assets/stylesheets/components/_homepage.scss
- the homepage gradient improved
=> homepage background gradient improved

app/views/trips/index.html.erb
- fixed Trip index page bug
- rewording to make trips time-insensitive
- added arrow for styling
=> Fix trips index page

app/controllers/reviews_controller.rb, app/controllers/side_quests_controller.rb, app/views/side_quests/_info_window.html.erb, app/views/side_quests/show.html.erb, app/views/trips/show.html.erb, config/routes.rb
many routes were broken and the links were pointing to controller methods that did not exist
this updates the link to reviews as well
reviews don't need to be nested in a trip. reviews are just for the sidequest.
sidequests now show the reviews that were made for that sidequest, not just the first two
=> fix paths and controllers and routes

app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_review.scss, app/assets/stylesheets/components/_trip-card.scss, app/views/devise/sessions/new.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb, app/views/shared/_navbar.html.erb, app/views/side_quests/_form.html.erb, app/views/side_quests/index.html.erb, app/views/side_quests/show.html.erb, app/views/trips/_info_window.html.erb, app/views/trips/edit.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb, config/initializers/simple_form_bootstrap.rb
- all btn are consistent font size 
- navbar recenserad to perfectly center
- added a add a review btn to sqs that has no reviews
=> recentered logo in the middle among minor changes

app/assets/stylesheets/components/_homepage.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
- fixed the page lagging for rending the homepage 
- removed the un-necessary head tags in the homepage partial ie; the mapboxapi link, commented out javascript include tag on said partial
=> Moses minor bug fix

app/controllers/trips_controller.rb, app/views/trips/show.html.erb
PLEASE TEST THOROUGHLY BEFORE MERGING
I haven't run through the demo flow because I don't know what the new flow is, so make sure this passes the entire process before merging. We don't want to introduce any new bugs.
**What does this do?**
- Creates a link from the Navigate button on the Trips#show page that directs to a google maps driving directions page. It include the stops along the route.
Make sure to test with the trip you take, so that we know the stops are in order and the result can be predictable.
=> Add link to google maps from Navigate button
